name: Static analysis

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.7.0
    with:
      local_package_names: edlfs

  call-secrets-analysis-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.7.0
